name: Build all platforms

on: [push]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: eskatos/gradle-command-action@v1
      with:
        gradle-version: 6.1.1
        arguments: :android:build

  build-ktor:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: 6.1.1
          arguments: :ktor:build

  build-react:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: 6.1.1
          arguments: :react:build
