# This is a basic workflow to help you get started with Actions

name: Build all platforms

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push, pull_request]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: eskatos/gradle-command-action@v1
      with:
        gradle-version: 5.5.1
        arguments: :android:build

  build-ktor:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: 5.5.1
          arguments: :ktor:build

  build-react:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: 5.5.1
          arguments: :react:build
