name: Static code analysis

on: [pull_request]

jobs:
  ktlint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: eskatos/gradle-command-action@v1
      with:
        gradle-version: 6.1.1
        arguments: ktlintCheck

  detekt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: 6.1.1
          arguments: detekt
